# Numpy

In [29]:
import numpy as np

In [30]:
list1 = [1,2,3,4,5]

In [31]:
array1 = np.array(list1)

In [32]:
array1

array([1, 2, 3, 4, 5])

In [33]:
type(array1)

numpy.ndarray

In [34]:
print(array1)

[1 2 3 4 5]


In [35]:
array1.size

5

In [36]:
array1.shape

(5,)

In [37]:
array1.dtype

dtype('int32')

In [38]:
list2 = [4,5,2,8,5]
list3 = [0,4,6,2,7]
list4 = [4,7,1,9,4]

In [39]:
array2 = np.array([list2,list3,list4])

In [40]:
array2

array([[4, 5, 2, 8, 5],
       [0, 4, 6, 2, 7],
       [4, 7, 1, 9, 4]])

In [41]:
array2.shape

(3, 5)

In [42]:
array2.size

15

In [43]:
array2.reshape(5,3)

array([[4, 5, 2],
       [8, 5, 0],
       [4, 6, 2],
       [7, 4, 7],
       [1, 9, 4]])

In [44]:
array2.shape

(3, 5)

# Indexing in Numpy Array

In [45]:
array3 = np.array([5,6,7,8,9])

In [46]:
print(array3)

[5 6 7 8 9]


In [47]:
array3[3]

8

In [48]:
array2

array([[4, 5, 2, 8, 5],
       [0, 4, 6, 2, 7],
       [4, 7, 1, 9, 4]])

In [49]:
array2[1:3,2:4]

array([[6, 2],
       [1, 9]])

In [50]:
array4 = np.arange(0,20,2)

In [51]:
array4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [53]:
array5 = [4,5,6,7,8,9,10,11]

In [54]:
array6 = array5.copy()

In [55]:
array5[4] = 5

In [56]:
array5

[4, 5, 6, 7, 5, 9, 10, 11]

In [57]:
array6

[4, 5, 6, 7, 8, 9, 10, 11]

In [60]:
np.arange(0,20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [62]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.random.rand(3,2)

array([[0.98364151, 0.44370513],
       [0.23314595, 0.005939  ],
       [0.66223614, 0.86968316]])

In [70]:
np.random.randn(5,4)

array([[-0.44793467,  0.66119059, -0.73000469, -0.72284612],
       [-0.6495082 ,  0.46757012, -0.10672317, -0.34293344],
       [ 0.02901574, -0.19683766,  0.04694515,  0.79813758],
       [ 2.35669315,  1.44506781,  0.77083004, -0.47411864],
       [ 0.44159551,  0.04716052, -0.9618069 , -0.83014377]])